### ISSUE TITLE
Could you please help me with the files changes and where to chage with fresh laravel app

### ISSUE THREAD

**Issue by Mashuk-EIS** [sagarankoliya/laravel-event-broadcasting-socket.io#1]
Hello, Hope you are doing fine.
I am new with websocket and trying to build a push notification system with it.
could you please mention or provide me a doc which files need to be changed or from where to start or where to end.
I have already installed everything as you suggested and i got the response from multiple browsers.

If you could guide me,I would be very thankful.

Regards
Mashuk

**Comment by sagarankoliya** [comment]
Hii

You can start with below file

resources/views/welcome.blade.php
app/Events/NewComment.php

This is only basic, call event from welcome file and broadcast from NewComment file and also one event listener added in welcome file which has listen incoming channel event

Let me know if anything unclear.

Thanks,
Sagar
